#!/usr/bin/env node

/*global process require exports setInterval */

var util = require('util'),
    pcap         = require("pcap"), pcap_session,
    dns_cache    = pcap.dns_cache,
    tcp_tracker  = new pcap.TCP_tracker();
    
if (process.argv.length > 4) {
    util.error("usage: tcp_metrics interface filter");
    util.error("Examples: ");
    util.error('  tcp_metrics "" "tcp port 80"');
    util.error('  tcp_metrics eth1 ""');
    util.error('  tcp_metrics lo0 "ip proto \\tcp and tcp port 80"');
    process.exit(1);
}

pcap_session = pcap.createSession(process.argv[2], process.argv[3]);

util.puts("Listening on " + pcap_session.device_name);

// Check for pcap dropped packets on an interval
setInterval(function () {
    var stats = pcap_session.stats();
    if (stats.ps_drop > 0) {
        util.puts("pcap dropped packets: " + util.inspect(stats));
    }
}, 2000);

tcp_tracker.on('start', function (session) {
    console.log("Start of TCP session between " + session.src_name + " and " + session.dst_name);
});

tcp_tracker.on('end', function (session) {
    console.log("End of TCP session between " + session.src_name + " and " + session.dst_name);
    console.log("Set stats for session: " + util.inspect(tcp_tracker.session_stats(session)));
});

// listen for packets, decode them, and feed TCP to the tracker
pcap_session.on('packet', function (raw_packet) {
    var packet = pcap.decode.packet(raw_packet);

    tcp_tracker.track_packet(packet);
});
